{% set name = "aiodns" %}
{% set version = "4.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: cb10e0c0d2591636716ad2fe402e977c16d71bdaf76bb8cb49e8a6633596f736

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools
    - pycares
  run:
    - python
    - pycares >=5.0.0,<6
    - uvloop >=0.22.1  # [not win]
    - winloop >=0.3.1  # [win]

test:
  source_files:
    - tests
  imports:
    - aiodns
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest tests
  requires:
    - pip
    - pytest >=8.4.1
    - pytest-tornasync

about:
  home: https://github.com/aio-libs/aiodns
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple DNS resolver for asyncio
  description: |
    aiodns provides a simple way for doing asynchronous DNS resolutions using
    pycares.
  doc_url: https://github.com/aio-libs/aiodns/blob/master/README.rst
  dev_url: https://github.com/aio-libs/aiodns

extra:
  recipe-maintainers:
    - CurtLH
